version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t jbeezley/tox:latest .
      - run: docker login --username jbeezley --password "$DOCKERHUB_REGISTRY_PASSWORD"
      - run: docker push jbeezley/tox:latest
